/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary':                    '#000000',
        'secondary':                  '#006a61',
        'background':                 '#f8f9ff',
        'surface':                    '#f8f9ff',
        'surface-dim':                '#cbdbf5',
        'surface-bright':             '#f8f9ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#eff4ff',
        'surface-container':          '#e5eeff',
        'surface-container-high':     '#dce9ff',
        'surface-container-highest':  '#d3e4fe',
        'surface-variant':            '#d3e4fe',
        'on-surface':                 '#0b1c30',
        'on-surface-variant':         '#45464d',
        'outline':                    '#76777d',
        'outline-variant':            '#c6c6cd',
        'secondary-container':        '#86f2e4',
        'secondary-fixed':            '#89f5e7',
        'secondary-fixed-dim':        '#6bd8cb',
        'on-secondary':               '#ffffff',
        'on-secondary-container':     '#006f66',
        'on-secondary-fixed':         '#00201d',
        'on-secondary-fixed-variant': '#005049',
        'tertiary-container':         '#07006c',
        'tertiary-fixed':             '#e1e0ff',
        'tertiary-fixed-dim':         '#c0c1ff',
        'on-tertiary':                '#ffffff',
        'on-tertiary-container':      '#7073ff',
        'on-tertiary-fixed':          '#07006c',
        'on-tertiary-fixed-variant':  '#2f2ebe',
        'primary-container':          '#131b2e',
        'primary-fixed':              '#dae2fd',
        'primary-fixed-dim':          '#bec6e0',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#7c839b',
        'on-primary-fixed':           '#131b2e',
        'on-primary-fixed-variant':   '#3f465c',
        'inverse-primary':            '#bec6e0',
        'inverse-surface':            '#213145',
        'inverse-on-surface':         '#eaf1ff',
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'on-error-container':         '#93000a',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg':      '0.5rem',
        'xl':      '0.75rem',
        'full':    '9999px',
      },
      spacing: {
        'base':           '8px',
        'stack-sm':       '12px',
        'stack-md':       '24px',
        'stack-lg':       '48px',
        'gutter':         '24px',
        'margin-mobile':  '16px',
        'margin-desktop': '40px',
        'container-max':  '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display':            ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':        ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-md':        ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm':        ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':            ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':            ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':            ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md':           ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'label-sm':           ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
}
